### ISSUE TITLE
createSvgFavicon is not a function

### ISSUE THREAD

**Issue by JP-Ellis** [faviator/faviator#19]
I tried using this and for some reason I'm getting the following error message:

```
npx faviator --size '230' --text 'F' --dx '-2.5' --dy '2' --font-size '70' --font-family 'Dancing Script' --font-color '#ffffff' --background-color '#f5beb7' --border-width '3.5' --border-color '#feeeec' --border-radius '50'
TypeError: createSvgFavicon is not a function
    at Function.faviator.svg (/tmp/josh/tmp.jw906G3dIx/node_modules/.pnpm/faviator@1.3.2/node_modules/faviator/lib/index.js:8:31)
    at main (/tmp/josh/tmp.jw906G3dIx/node_modules/.pnpm/faviator@1.3.2/node_modules/faviator/bin/faviator.js:43:41)
    at Object.<anonymous> (/tmp/josh/tmp.jw906G3dIx/node_modules/.pnpm/faviator@1.3.2/node_modules/faviator/bin/faviator.js:76:1)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

I have tried installing this with `pnpm`, `yarn` and `npm`, all resulting in this error.

Some information about my system:

```
node --version
v14.8.0
yarn --version
1.22.4
npm --version
6.14.7
```

and the contents of `package.json`:

```json
{
  "dependencies": {
    "faviator": "^1.3.2"
  }
}
```
```

**Comment by JP-Ellis** [comment]
Doing a little a debugging, it seems like the following fixes the issue (within `faviator/lib/index.js`):

```
- const createSvgFavicon = require('@faviator/create-svg-favicon');
+ const createSvgFavicon = require('@faviator/create-svg-favicon').default;
```

I'm fairly new to the whole Node structure, so I'm not sure why this is.

**Comment by ycmjason** [comment]
Thanks. I'll be looking into this today.

Meanwhile feel free to use https:://faviator.xyz to download the favicon you want.

**Comment by ycmjason** [comment]
fixed https://github.com/faviator/faviator/commit/0d3c12ec56e4ba913a814cef9b408487464e998a
