### ISSUE TITLE
Fails to work in WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by cfjedimaster** [faviator/faviator#3]
When trying to generate an icon, I get:

```
ray@DeathStar:/mnt/c/projects/raymondcamdendotcom$ faviator --size '230' --text 'RC' --dx '-2.5' --dy '20.5' --font-size '70' --font-family 'Dancing Script'
 --font-color '#ffffff' --background-color '#ff0000' --border-width '3.5' --border-color '#feeeec' --border-radius '50' --output favicon.png
Writting to favicon.png...
{ Error: kill ESRCH
    at Object._errnoException (util.js:1021:11)
    at process.kill (internal/process.js:180:18)
    at forceKillChrome (/home/ray/.nvm/versions/node/v8.7.0/lib/node_modules/faviator/node_modules/puppeteer/lib/Launcher.js:181:19)
    at Function.launch (/home/ray/.nvm/versions/node/v8.7.0/lib/node_modules/faviator/node_modules/puppeteer/lib/Launcher.js:156:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
```

**Comment by ycmjason** [comment]
I am really sorry to hear this. This sounds like an issue to do with [puppeteer](https://github.com/GoogleChrome/puppeteer). 

Faviator uses puppeteer to spin up a headless chrome in order to capture the svg icon.

I have found [this](https://github.com/GoogleChrome/puppeteer/issues/1837) which addresses the issue I think you are having.
